#!/bin/bash
file=.pio/build/nanoatmega328new/firmware.hex
if [ ! -f "$file" ] ; then
    echo "Compiled binary file does not exist."
    exit 1
fi

id="$(git describe --dirty --always)"

filename=$(basename "$file")
newfile="${filename/.hex/_$id.hex}"
echo "$newfile"

chmod -x "$file"
mkdir -p bin/
mv -i "$file" "bin/$newfile"
cp -n ~/.platformio/packages/tool-avrdude/avrdude.conf tools/
rsync -avR -e ssh tools/avrdude.conf tools/upload_latest "bin/$newfile" ntb1:source/repos/elektromer-logger/
